-- Seed data: 44 European countries
-- Format: INSERT INTO countries (iso, label, active) VALUES (...);

INSERT INTO countries (iso, label, active) VALUES
    ('AD', 'Andorra', true),
    ('AL', 'Albania', true),
    ('AT', 'Austria', true),
    ('BA', 'Bosnia and Herzegovina', true),
    ('BE', 'Belgium', true),
    ('BG', 'Bulgaria', true),
    ('CH', 'Switzerland', true),
    ('CY', 'Cyprus', true),
    ('CZ', 'Czechia', true),
    ('DE', 'Germany', true),
    ('DK', 'Denmark', true),
    ('EE', 'Estonia', true),
    ('ES', 'Spain', true),
    ('FI', 'Finland', true),
    ('FR', 'France', true),
    ('GB', 'United Kingdom', true),
    ('GR', 'Greece', true),
    ('HR', 'Croatia', true),
    ('HU', 'Hungary', true),
    ('IE', 'Ireland', true),
    ('IS', 'Iceland', true),
    ('IT', 'Italy', true),
    ('LI', 'Liechtenstein', true),
    ('LT', 'Lithuania', true),
    ('LU', 'Luxembourg', true),
    ('LV', 'Latvia', true),
    ('MC', 'Monaco', true),
    ('MD', 'Moldova', true),
    ('ME', 'Montenegro', true),
    ('MK', 'North Macedonia', true),
    ('MT', 'Malta', true),
    ('NL', 'Netherlands', true),
    ('NO', 'Norway', true),
    ('PL', 'Poland', true),
    ('PT', 'Portugal', true),
    ('RO', 'Romania', true),
    ('RS', 'Serbia', true),
    ('SE', 'Sweden', true),
    ('SI', 'Slovenia', true),
    ('SK', 'Slovakia', true),
    ('SM', 'San Marino', true),
    ('TR', 'Turkiye', true),
    ('UA', 'Ukraine', true),
    ('XK', 'Kosovo', true)
ON CONFLICT (iso) DO NOTHING;
