-- Seed data: 44 European countries
-- Format: INSERT INTO countries (iso, label, active) VALUES (...);

INSERT INTO countries (iso, label, active) VALUES
    ('AD', 'Andorra', false),
    ('AL', 'Albania', false),
    ('AT', 'Austria', false),
    ('BA', 'Bosnia and Herzegovina', false),
    ('BE', 'Belgium', true),
    ('BG', 'Bulgaria', true),
    ('CH', 'Switzerland', false),
    ('CY', 'Cyprus', false),
    ('CZ', 'Czechia', false),
    ('DE', 'Germany', false),
    ('DK', 'Denmark', false),
    ('EE', 'Estonia', false),
    ('ES', 'Spain', true),
    ('FI', 'Finland', false),
    ('FR', 'France', false),
    ('GB', 'United Kingdom', false),
    ('GR', 'Greece', false),
    ('HR', 'Croatia', false),
    ('HU', 'Hungary', false),
    ('IE', 'Ireland', false),
    ('IS', 'Iceland', false),
    ('IT', 'Italy', false),
    ('LI', 'Liechtenstein', false),
    ('LT', 'Lithuania', false),
    ('LU', 'Luxembourg', false),
    ('LV', 'Latvia', false),
    ('MC', 'Monaco', false),
    ('MD', 'Moldova', false),
    ('ME', 'Montenegro', false),
    ('MK', 'North Macedonia', false),
    ('MT', 'Malta', false),
    ('NL', 'Netherlands', false),
    ('NO', 'Norway', false),
    ('PL', 'Poland', false),
    ('PT', 'Portugal', false),
    ('RO', 'Romania', false),
    ('RS', 'Serbia', true),
    ('SE', 'Sweden', false),
    ('SI', 'Slovenia', false),
    ('SK', 'Slovakia', false),
    ('SM', 'San Marino', false),
    ('TR', 'Turkiye', false),
    ('UA', 'Ukraine', false),
    ('XK', 'Kosovo', false)
ON CONFLICT (iso) DO NOTHING;
